wandb_version: 1

Unique Run ID:
  desc: null
  value: d48624b4
_wandb:
  desc: null
  value:
    cli_version: 0.10.17
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.5
      5: 0.10.17
      8:
      - 1
batch_size:
  desc: null
  value: 16
depth:
  desc: null
  value: 1
drop_prob:
  desc: null
  value: 0.0
embed_dim:
  desc: null
  value: 16
epochs:
  desc: null
  value: 2
heads:
  desc: null
  value: 1
hidden:
  desc: null
  value: 16
job_dir:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 0.01
lr_scheduler:
  desc: null
  value: plateau
manual_seed:
  desc: null
  value: 42
model_type:
  desc: null
  value: attention
name_run:
  desc: null
  value: first_trial
num_workers:
  desc: null
  value: 0
patience:
  desc: null
  value: 1
split_method:
  desc: null
  value: random
wandb:
  desc: null
  value: true
within_epoch_interval:
  desc: null
  value: 5
